version: '3.8'
services:
  db:
    image: postgres:13.18
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080" # Map container's 8080 to host's 8081