-- Create accounts table
CREATE TABLE t_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255) NOT NULL,
    balance NUMERIC(19,2) NOT NULL,
    account_type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_on TIMESTAMP,
    updated_on TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES t_user(id)
);

-- changeset author:add-relationships-to-entities
-- Add account_id column to transactions table
ALTER TABLE t_transaction ADD COLUMN account_id BIGINT;
ALTER TABLE t_transaction ADD COLUMN employee_id BIGINT;


-- Add foreign key for account_id in transactions table
ALTER TABLE t_transaction
ADD CONSTRAINT fk_account_id
FOREIGN KEY (account_id)
REFERENCES t_account (id);

-- Add foreign key for employee_id in transactions table
ALTER TABLE t_transaction
ADD CONSTRAINT fk_employee_id
FOREIGN KEY (employee_id)
REFERENCES t_employee (id);

